const fs=require('fs');
const h=fs.readFileSync('/Users/tungyeh/Projects/yugym-booking-system-app/index.html','utf8');
const i=h.indexOf('const _bkFee=(b,tk)=>{');
const src=h.slice(i, h.indexOf('};', i)+2);
const _bkFee=new Function(src+'; return _bkFee;')();
let pass=0,fail=0;
const chk=(n,got,want)=>{const ok=got===want;ok?pass++:fail++;console.log(`  ${ok?'✓':'✗'} ${n}  got=${got} want=${want}`);};
console.log('PostgREST 回傳字串型 numeric：');
chk('unit_price 字串 "0" 不再吃掉 session_fee', _bkFee({session_fee:'1100'},{unit_price:'0'}), 1100);
chk('session_fee 字串正常轉數字', _bkFee({session_fee:'1422.2'},{unit_price:'1422'}), 1422.2);
console.log('優先序：');
chk('有 session_fee 就用它', _bkFee({session_fee:'1000'},{unit_price:'1500'}), 1000);
chk('session_fee 為 0 也算數（免費課）', _bkFee({session_fee:'0'},{unit_price:'1500'}), 0);
chk('session_fee 為 null → 用票券單價（新系統預約）', _bkFee({session_fee:null},{unit_price:'1600'}), 1600);
console.log('邊界：');
chk('兩者皆無 → 0', _bkFee({session_fee:null},null), 0);
chk('沒有票券也不報錯', _bkFee({session_fee:'800'},null), 800);
chk('空字串視為無值', _bkFee({session_fee:''},{unit_price:'900'}), 900);
chk('unit_price 為 null → 0', _bkFee({session_fee:null},{unit_price:null}), 0);
console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail?1:0);
