const fs=require('fs');
const h=fs.readFileSync('/Users/tungyeh/Projects/yugym-booking-system-app/index.html','utf8');
const a=h.indexOf('const _tkPaid=t=>');
const b=h.indexOf('const revTickets=', a);
const api=new Function(h.slice(a,b)+'; return {_tkPaid,_tkBuyDate};')();
let pass=0,fail=0;
const chk=(n,got,want)=>{const ok=got===want;ok?pass++:fail++;console.log(`  ${ok?'✓':'✗'} ${n}  got=${JSON.stringify(got)} want=${JSON.stringify(want)}`);};
console.log('金額（PostgREST numeric 回字串）：');
chk('字串金額轉數字', api._tkPaid({amount_paid:'5000'}), 5000);
chk('小數金額', api._tkPaid({amount_paid:'1422.2'}), 1422.2);
chk('null → 0', api._tkPaid({amount_paid:null}), 0);
chk('缺欄位 → 0', api._tkPaid({}), 0);
chk('空字串 → 0', api._tkPaid({amount_paid:''}), 0);
console.log('加總不再變成字串相接：');
const sum=[{amount_paid:'5000'},{amount_paid:'3000'}].reduce((s,t)=>s+api._tkPaid(t),0);
chk('5000+3000=8000（非 "050003000"）', sum, 8000);
console.log('購買日：');
chk('有 purchase_date 就用它', api._tkBuyDate({purchase_date:'2026-07-14',start_date:'2026-07-21'}), '2026-07-14');
chk('沒有就退回 start_date', api._tkBuyDate({purchase_date:null,start_date:'2026-06-18'}), '2026-06-18');
chk('兩者皆無 → null', api._tkBuyDate({purchase_date:null,start_date:null}), null);
console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail?1:0);
