const fs=require('fs');
const h=fs.readFileSync('index.html','utf8');
const grab=n=>{const i=h.indexOf('function '+n+'(');let d=0;for(let k=h.indexOf('{',i);k<h.length;k++){if(h[k]==='{')d++;else if(h[k]==='}'){d--;if(!d)return h.slice(i,k+1);}}};
const src=[grab('tkVisual'),grab('ticketTokens')].join('\n');
const COURSE_SHAPE={};
const parseYmd=s=>{const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(s||'');return m?new Date(+m[1],+m[2]-1,+m[3]):null;};
const api=new Function('COURSE_SHAPE','parseYmd', src+'; return {ticketTokens};')(COURSE_SHAPE,parseYmd);
const tm={'tt-pt':{id:'tt-pt',name:'教練課',category:'私人教練',color:'pt'}};
const tk={ticket_type_id:'tt-pt',sessions_total:4,plan_name:'私人教練課 1V1'};
const B=(id,d,st)=>({id,date:d,start_time:'09:00',status:st});
let pass=0,fail=0;
const chk=(n,c)=>{c?pass++:fail++;console.log(`  ${c?'✓':'✗'} ${n}`);};

let s=api.ticketTokens(tk,[B('b1','2026-07-01','completed'),B('b2','2026-07-08','checked_in'),B('b3','2026-07-31','booked')],tm,2,'b3');
console.log('日期顯示：');
chk('已完成顯示 7/1', s.includes('>7/1<'));
chk('已完成顯示 7/8', s.includes('>7/8<'));
chk('已預約顯示 7/31', s.includes('>7/31<'));
chk('不再顯示序號 1/2/3 當內容', !/>1<|>2<|>3<|>4</.test(s));
console.log('本堂標記：');
chk('本堂加 mtk-cur', s.includes('mtk-cur'));
chk('本堂只有一個', (s.match(/mtk-cur/g)||[]).length===1);
chk('title 標「本堂」', s.includes('（本堂）'));
chk('未使用仍為空心', s.includes('mtk-free'));
console.log('相容性（其他呼叫端不傳 curId）：');
let s2=api.ticketTokens(tk,[B('b1','2026-07-01','completed')],tm,1);
chk('不傳 curId 就沒有金框', !s2.includes('mtk-cur'));
chk('仍正常顯示日期', s2.includes('>7/1<'));
console.log('分期鎖定：');
let s3=api.ticketTokens({...tk,installment:{current:2},unlocked_sessions:2},[],tm,0);
chk('未開通顯示鎖頭', (s3.match(/mtk-lock/g)||[]).length===2);
console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail?1:0);
