-- 2026-08-05 使用者指示（魚媽劉媽案例）：「親友自主訓練的票券簽到就不用再贈送自主訓練點數了」
-- （已套用）三件一起處理：
-- ① 資料修正：46 筆匯入的自主訓練預約 benefit_type 誤標 coaching_session → 改 training_pass
-- ② 作廢 3 張誤發的自主訓練點數券（0 使用，status→refunded 並留 note）
-- ③ handle_checkin_reward 加課種保險：只有 私人教練/體驗（或 coach_leave 補償）才發點，
--    benefit_type 再被誤標也擋得住。完整函式定義見 Supabase migration
--    checkin_reward_category_guard（此檔為摘要備忘）。
--
-- ⚠ 同日 19:0x 修正：課種保險的 b.status <> 'coach_leave' 直接比 enum，
--    但 booking_status enum 沒有 coach_leave 值 → 每一筆簽到（會員端/櫃檯 RPC）
--    都在這裡炸掉、整包 rollback，表現為「簽到被擋權限」。
--    改為 b.status::text <> 'coach_leave'。已用真實課卡（自主訓練＋教練課）
--    以會員身分實測：自主訓練簽到成功且不發點、教練課簽到成功且發點。
--
-- 2026-08-06 三修（使用者回報：施佩怡 7/31 有簽到但沒送自主訓練）：
--   原本只有 category='私人教練' 才會推定 benefit_type，於是
--   ①體驗課（無 benefit_type、無票券）②教練課但簽到當下還沒綁票 → 規則對不上、一律 skipped。
--   改成教練課／體驗／教練請假一律有預設值（有票且含「友善」→ friendly_session，其餘 coaching_session）。
--   已補發 3 筆漏發（施佩怡 7/31、林孟玉 8/4、陳詠菱 8/4；楊鈞亦 7/25 早已另有 3 筆贈點故不重複補）。
