-- 2026-08-14（已於當日套用正式庫）
-- 使用者定案：「教練請假這堂先釋出的話，教練把釋出的堂數往後面預約了，這堂課就會變得奇怪
-- —— 要等會員來上課簽到才能釋出這堂課」
-- 改版：教練請假當下「堂數不退、票繼續掛在預約上」（防止堂數被挪去約別的課），
-- 效期展延照舊在請假當下給；堂數改在兩個時點釋出：
--   ①會員到場簽到 → fn_checkin_booking 內退回 1 堂＋解綁（本檔重建整支函式，新增 1.5 節）
--   ②這堂被取消 → 取消視窗改走「退回票券」（前端 confirmCancelBooking coach_leave 分支）
-- 復原教練請假：新制沒退過堂 → 不需扣回，只還原課種/狀態＋效期回調（前端 _bkCoachLeaveUndo）。
-- 舊制資料（請假時已退、票已解綁）兩條路都向下相容。
-- 函式全文見 Supabase fn_checkin_booking（新增段落）：
--   IF coalesce(b.coach_leave,false) AND b.ticket_id IS NOT NULL THEN
--     UPDATE member_tickets SET sessions_remaining=sessions_remaining+1,
--       status=CASE WHEN status='used_up' THEN 'usable' ELSE status END WHERE id=b.ticket_id;
--     INSERT INTO ticket_logs (...) VALUES (gen_short_id('LG-'), b.ticket_id,'refund',1,b.id,'system',
--       '教練請假：會員到場簽到，堂數退回（請假當下不退的新制）');
--     UPDATE bookings SET ticket_id=NULL WHERE id=b.id;
--   END IF;

-- ── 2026-08-14 晚間二修（已套用正式庫）──────────────────────────
-- ①簽到釋出「不再解綁 ticket_id」：圓形卡的「課種色填滿＋紅圈」獨立加值圓點
--   要靠 ticket_id 才畫得出來；防重複退靠 checked_in_at 冪等（函式開頭已擋）。
--   （上面引文中的 UPDATE bookings SET ticket_id=NULL 那行已移除。）
-- ②Mango 8/20–8/24 請假 18 堂是中午「舊制」請的（當場退堂＋解綁 → 課卡無紅圈），
--   已批次轉新制：ticket_id 掛回、堂數收回（LG-FIX-clv-<booking_id> deduct −1）、
--   備註補「（堂數待簽到或取消時退回；0814 舊制轉新制）」。帳本原本的退課紀錄保留，
--   與收回互相抵消，效期展延（請假當下已給）不動。
-- ③黃雅菁 8/21 19:00 櫃檯漏標 → 補標新制請假＋效期展延 +7（2027-07-30 → 2027-08-06，
--   LG-FIX-clv-BK-19ffeda0a42786a-ext）。
-- ④會員端不得自簽教練請假堂（同日三修，使用者指示「簽到一律由櫃檯負責，
--   以免會員在家就簽到根本沒到場」）：fn_checkin_booking 開頭新增
--   IF coalesce(b.coach_leave,false) AND p_checkin_source='member_app'
--     THEN RETURN error_code='BOOKING.DESK_ONLY'；前端按鈕與 checkInBooking 也各擋一層。
--   另新增「未到場結課」（前端 bkCoachLeaveNoShow，不經 RPC）：completed＋退堂＋不發點、
--   不寫 checked_in_at —— 圓形卡靠簽到時間分辨到場（實心紅圈點）／未到場（不畫點）。
