-- 2026-08-12（已套用正式庫）：員工端／會員端開放上傳照片（大頭貼）
-- members/employees 加 avatar_url；storage bucket 'avatars'（公開讀）
-- 寫入政策：櫃檯/管理員可傳任何人；會員/員工限自己的路徑（<kind>/<自己的id>.jpg）
-- 前端：資料頁點頭像上傳（縮 384px 置中裁切 JPEG）；員工列表與會員列表顯示照片。
